config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :customer_cards
  resources :customers do 
    resources :transactions
  end
  resources :cards
  resources :banks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank.rb
class Bank < ApplicationRecord
    has_many :cards
end

app/models/card.rb
class Card < ApplicationRecord
    has_many :customer_cards
    has_many :customers, through: :customer_cards
    has_many :transactions
    belongs_to :bank
    validates :name, uniqueness: true
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :customer_cards
    has_many :cards, through: :customer_cards
    has_many :transactions, dependent: :delete_all

    validates :name, presence: true
    validates :age, numericality: { greater_than: 19}
    validates :email, uniqueness: true, format: /\w+@\w+\.{1}[a-zA-Z]{2,}/
    validates :phone_number, length: {is: 10}

end

app/models/customer_card.rb
class CustomerCard < ApplicationRecord
    belongs_to :customer
    belongs_to :card
end

app/models/transaction.rb
class Transaction < ApplicationRecord
    belongs_to :card
    belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
    def show
        @bank=Bank.find(params[:id])
    end
    def index
        @banks=Bank.all
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
    def index
        @cards=Card.all 
    end 
    def show
        @card=Card.find(params[:id])
    end
    def new
        @card=Card.new
    end
    def create 
        @card=Card.new(card_params)
        if @card.save
            redirect_to card_path(@card)
        else
            render :new
        end
    end
    
    private
    def card_params
        params.require(:card).permit(:name,:bank_id)
    end
end

app/controllers/customer_cards_controller.rb
class CustomerCardsController < ApplicationController
    
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    def index
        @customers=Customer.all 
    end
    def show
        @customer=Customer.find(params[:id])
    end
    def new 
        @customer=Customer.new
    end
    def create
        @customer=Customer.new(customer_params)
        if @customer.valid?
            @customer.save
        redirect_to customer_path(@customer)
        else
            render :new 
        end
    end
    def edit
        @customer=Customer.find(params[:id])
    end
    def update
        @customer=Customer.find(params[:id])
        if @customer.update(customer_params)
        redirect_to customer_path(@customer)
        else 
            render :edit 
        end
    end

    def destroy
        @customer=Customer.find(params[:id])
        @customer.destroy
        redirect_to customers_path
    end

    private
    def customer_params
        params.require(:customer).permit(:name,:age, :phone_number,:address,:email,:salary, card_ids:[])
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
   def index
    @transactions=Transaction.all
   end

   def show
    @transaction=Transaction.find(params[:id])

   end

   def new 
    @transaction=Transaction.new
   end

   def create
    
    @transaction=Transaction.create(transaction_params)
    redirect_to transaction_path(@transaction)
   end

   private
   def transaction_params
    params.require(:transaction).permit(:amount, :card_id, :customer_id)
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/customer_cards_helper.rb
module CustomerCardsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/banks/index.html.erb
<h3 style="background-color:powderblue;padding:12px 24px">List of Banks</h3>
<hr>
<div style="background-color:#eeeeee;padding:6px 24px">
<% @banks.each do |bank| %>
    <h5 style="padding:0px 24px"><%= link_to bank.name, bank_path(bank) %></br></h5>
<% end %>
</div>

app/views/banks/show.html.erb
<h3 style="background-color:powderblue;padding:12px 24px">Bank Info</h3>
<hr>
<div style="background-color:#eeeeee;padding:6px 24px">
<h4><%= @bank.name %> </h4><br>
<img src="<%=@bank.img_url %>" width="300"></br>
<% @bank.cards.each do |card| %>
     <h5><li><%= card.name %></li></h5> 
<% end %>
</div>

app/views/cards/index.html.erb
<h3 style="background-color:powderblue;padding:12px 24px">List of Cards</h3>
<hr>
<div style="background-color:#eeeeee;padding:6px 24px">
<% @cards.each do |card| %>
    <h5 style="padding:0px 24px"><%= card.name %></br></h5>
<% end %>
</div>

app/views/cards/new.html.erb
<%= form_for @card do |f| %>

    <% if @card.errors.any? %>
        <div id="error_explanation" style="color:red;" >
            <ul> 
                <% @card.errors.full_messages.each do |mes| %>
                    <li><%= mes %> </li>
                <% end %>
            </ul>
        </div>
<% end %>
 <hr>
<h3 style="padding:12px 24px;background-color:powderblue">Card Form</h3>   
<div id="customer_form" style="background-color:#eeeeee;padding:6px 24px">
        <br/>
        <div style="padding: 2px 0"><%= f.label "Card Name: " %><%= f.text_field :name %></br></div>
        Please choose your Bank below:
        <p> 
        <%= f.collection_select :bank_id, Bank.all, :id, :name %></br>
        </p>
        <%= f.submit %>
    </div>
<% end %>

app/views/cards/show.html.erb
<h3 style="padding:12px 24px;background-color:powderblue">Card Info</h3>
<hr>
<div style="background-color:#eeeeee;padding:6px 24px">
Card Name:<%= @card.name %></br>
Bank: <%= @card.bank.name %></br>
</div>

app/views/customers/edit.html.erb
<h1> Edit File </h1>
<%= form_for @customer do |f| %>
    
    <% if @customer.errors.any? %>
        <div id="error_explanation" style="color:red;" >
            <ul> 
                <% @customer.errors.full_messages.each do |mes| %>
                    <li><%= mes %> </li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <hr>

    <h3 style="padding:12px 24px;background-color:powderblue">Customer Form</h3>
    
    <div id="customer_form" style="background-color:#eeeeee;padding:6px 24px">
        <br/>
        <div style="padding: 2px 0"><%= f.label "Name: " %><br/></div>
        <div style="padding: 2px 0"><%= f.text_field :name %><br/></div>
        <div style="padding: 2px 0"><%= f.label "Age: " %><br/></div>
        <div style="padding: 2px 0"><%= f.text_field :age %><br/></div>
        <div style="padding: 2px 0"><%= f.label "Phone Number: " %><br/></div>
        <div style="padding: 2px 0"><%= f.text_field :phone_number %><br/></div>
        <div style="padding: 2px 0"><%= f.label "Address: " %><br/></div>
        <div style="padding: 2px 0"><%= f.text_field :address %><br/></div>
        <div style="padding: 2px 0"><%= f.label "Email: " %><br/></div>
        <div style="padding: 2px 0"><%= f.text_field :email %><br/></div>
        <div style="padding: 2px 0"><%= f.label "Salary: " %><br/></div>
        <div style="padding: 2px 0"><%= f.text_field :salary %><br/></div>

        Please choose your card below:
        <p> 
            <%= f.collection_check_boxes :card_ids, Card.all, :id, :name %></br>
        </p>
        <%= f.submit %>
    </div>
<% end %>

app/views/customers/index.html.erb
<h3 style="background-color:powderblue;padding:12px 24px">List of Customers</h3>
<hr>
<div style="background-color:#eeeeee;padding:6px 24px">
<% @customers.each do |customer| %>
    <h5 style="padding:0px 24px"><%= link_to customer.name, customer_path(customer) %></br></h5>
<% end %>

</div>

app/views/customers/new.html.erb
<h1> New File </h1>

<%= form_for @customer do |f| %>
    
    <% if @customer.errors.any? %>

      
        <h3> Errors: </h3
        <div id="error_explanation" style="color:red" >
            <ul> 
                <% @customer.errors.full_messages.each do |mes| %>
                    <li><%= mes %> </li>
                <% end %>
            </ul>

        </div>
    <% end %>
    <hr>
    <h3 style="padding:12px 24px;background-color:powderblue">Customer Form</h3>
    
    <div id="customer_form" style="background-color:#eeeeee;padding:6px 24px">
        <br/>
        <div style="padding: 2px 0"><%= f.label "Name: " %><br/></div>
        <div style="padding: 2px 0"><%= f.text_field :name %><br/></div>
        <div style="padding: 2px 0"><%= f.label "Age: " %><br/></div>
        <div style="padding: 2px 0"><%= f.text_field :age %><br/></div>
        <div style="padding: 2px 0"><%= f.label "Phone Number: " %><br/></div>
        <div style="padding: 2px 0"><%= f.text_field :phone_number %><br/></div>
        <div style="padding: 2px 0"><%= f.label "Address: " %><br/></div>
        <div style="padding: 2px 0"><%= f.text_field :address %><br/></div>
        <div style="padding: 2px 0"><%= f.label "Email: " %><br/></div>
        <div style="padding: 2px 0"><%= f.text_field :email %><br/></div>
        <div style="padding: 2px 0"><%= f.label "Salary: " %><br/></div>
        <div style="padding: 2px 0"><%= f.text_field :salary %><br/></div>
        Please choose your card below:
        <p> 
            <%= f.collection_check_boxes :card_ids, Card.all, :id, :name %></br>
        </p>
        <%= f.submit %>
    </div>
<% end %>

app/views/customers/show.html.erb
<h3 style="padding:12px 24px;background-color:powderblue">Profile</h3>
<hr>
<div style="background-color:#eeeeee;padding:6px 24px">
    Name: <%= @customer.name %></br></br>
    Age: <%= @customer.age %></br></br>
    Phone Number: <%= @customer.phone_number %></br></br>
    Address: <%= @customer.address %></br></br>
    Email: <%= @customer.email %></br></br>
    Salary: <%= @customer.salary %></br></br>
    Account: </br>
    <div style="padding-left:16px">
    <% @customer.cards.each do |card| %>
        <li> <%=card.name %> </br>
    <% end %>
    </div>
    </br>
    Transactions: 
    <div style="padding-left:16px">
    <% @customer.transactions.each do |trans| %>
        <li> <%=trans.card.name %> </br>
            - $<%= trans.amount %> made on <%= trans.created_at.strftime("%m/%d/%Y")%></li>
    <% end %>
   </br>
    </div>
</div>
</br>
<div>
<div>
    <%= link_to "Edit", edit_customer_path(@customer) %>
    <%= link_to 'Delete', customer_path(@customer), method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/transactions/index.html.erb
<body style="background-color:#eeeeee;">
<h3 style="background-color:powderblue;padding:12px 24px">List of Transactions</h3>
<hr>
<% @transactions.each do |tran| %>
    <h5 style="padding:0px 24px"><%= link_to tran.customer.name, transaction_path(tran) %> - <%= tran.card.name %> - $<%= tran.amount %><br><br></h5>
<% end %>

app/views/transactions/new.html.erb
<h3 style="padding:12px 24px;background-color:powderblue">New Transaction</h3>
 <hr>
 <div id="customer_form" style="background-color:#eeeeee;padding:6px 24px">
        <br/>
<%= form_for @transaction do |f| %>
    <div style="padding: 2px 0"><%= f.label "Amount " %><br/></div>
    <div style="padding: 2px 0"><%= f.text_field :amount %></br></div>
    <div style="padding: 2px 0"> <%= f.label "Customer" %><br/></div>
    <div style="padding: 2px 0"><%= f.collection_select :customer_id, Customer.all, :id, :name %><br/></div>
    <div style="padding: 2px 0"><%= f.label "From" %><br/></div>
    <div style="padding: 2px 0"><%= f.collection_select :card_id, Card.all, :id, :name %></br></br></div>
    <div style="padding: 2px 0"><%= f.submit %> </br></div>
    </div>
<% end %>

app/views/transactions/show.html.erb
<h3 style="padding:12px 24px;background-color:powderblue">Transaction Details</h3>
<hr>
<div style="background-color:#eeeeee;padding:6px 24px">
Amount: <%= @transaction.amount %></br></br>
Customer: <%= link_to @transaction.customer.name, customer_path(@transaction.customer.id)%></br></br>
Card: <%= @transaction.card.name %></br></br>
Time: <%= Time.now.strftime (" %m/%d/%Y") %></br></br>
</div>